//! The app half of `Services/Subsonic/SubsonicResponseBuilder*.cs`.
//!
//! The builder itself, with every shape that needs only the models, is
//! [`octo_subsonic::subsonic_response_builder::SubsonicResponseBuilder`]; its answers are
//! [`SubsonicReply`] values, which are axum responses (`IntoResponse`: 200, the content type the
//! ASP.NET result wrote, and a `Content-Length`). This module wires it to the app:
//!
//! - [`ExternalIdRegistry`] is its id registry;
//! - [`new_subsonic_response_builder`] builds it from the settings, read once (`IOptions`);
//! - [`SubsonicResponseBuilderExt`] adds the answers that take app-service types: an
//!   acquisition snapshot, a generated mix, a library-action outcome and an upgrade job.

use std::sync::Arc;

use chrono::{DateTime, Utc};
use octo_core::common::dotnet::to_lower_invariant;
use octo_core::json::dom::Node;
use octo_core::settings::{GeneratedPlaylistSettings, SubsonicSettings};
use octo_core::soulseek::SoulseekRouting;
use octo_subsonic::subsonic_response_builder::{
    Fields, IdRegistry, REMOVE_ACTION, SUBSONIC_VERSION, SubsonicReply, SubsonicResponseBuilder,
};
use serde_json::{Value, json};

use crate::services::common::acquisition_tracker::AcquisitionSnapshot;
use crate::services::library::{GeneratedPlaylist, LibraryActionOutcome, UpgradeJob};
use crate::services::soulseek::ExternalIdRegistry;

impl IdRegistry for ExternalIdRegistry {
    fn register(&self, routing: SoulseekRouting) -> String {
        ExternalIdRegistry::register(self, routing)
    }
}

/// The builder as `Program.cs` registered it: over the app's id registry, with
/// `Subsonic:WaitForLosslessOnPlay` read once here (it decides what every row declares, and
/// is restart-required).
pub fn new_subsonic_response_builder(
    id_registry: Arc<ExternalIdRegistry>,
    subsonic: &SubsonicSettings,
) -> SubsonicResponseBuilder {
    SubsonicResponseBuilder::new(id_registry, subsonic)
}

/// The builder's answers that take app-service types.
pub trait SubsonicResponseBuilderExt {
    /// getAcquisitions: the caller's own downloads in flight or recently ended. Always JSON,
    /// whatever format was asked for; the only client that reads it parses JSON, and the
    /// extension it is advertised under says so.
    fn create_acquisitions_response(&self, rows: &[AcquisitionSnapshot]) -> SubsonicReply;

    /// A mix as a playlist row: the same keys a radio station has, read-only (#54).
    fn generated_playlist_fields(
        &self,
        mix: &GeneratedPlaylist,
        settings: &GeneratedPlaylistSettings,
    ) -> Fields;

    /// A mix with its songs. The songs are Navidrome's own, passed through as Navidrome described
    /// them; in XML only their scalar fields, since Subsonic's XML entry is attribute-only.
    fn create_generated_playlist_response(
        &self,
        format: &str,
        mix: &GeneratedPlaylist,
        settings: &GeneratedPlaylistSettings,
        entries: &[Node],
    ) -> SubsonicReply;

    /// libraryAction: what happened to one request. Always ok, so the client reads the state
    /// rather than an error, even when nothing was done. (C#'s default action is
    /// [`REMOVE_ACTION`].)
    fn create_library_action_outcome_response(
        &self,
        song_id: &str,
        outcome: &LibraryActionOutcome,
        action: &str,
    ) -> SubsonicReply;

    /// getUpgrades: the caller's upgrade jobs, a plain array under "upgrades". The id is the
    /// Navidrome id that was asked for, and it stays the same after the swap. progress is 0 to
    /// 1, or null.
    fn create_upgrades_response(&self, jobs: &[(UpgradeJob, Option<f64>)]) -> SubsonicReply;
}

impl SubsonicResponseBuilderExt for SubsonicResponseBuilder {
    fn create_acquisitions_response(&self, rows: &[AcquisitionSnapshot]) -> SubsonicReply {
        self.create_json_response(json!({
            "status": "ok",
            "version": SUBSONIC_VERSION,
            "type": "octo",
            "acquisitions": {
                "acquisition": rows.iter().map(|row| Value::Object(acquisition_json(row))).collect::<Vec<_>>(),
            },
        }))
    }

    fn generated_playlist_fields(
        &self,
        mix: &GeneratedPlaylist,
        settings: &GeneratedPlaylistSettings,
    ) -> Fields {
        let song_count = settings.effective_track_count().min(mix.pool_size);
        let mut fields = Fields::new();
        fields.insert("id".into(), mix.id.clone().into());
        fields.insert("name".into(), mix.name.clone().into());
        fields.insert("owner".into(), mix.owner.clone().into());
        fields.insert("public".into(), false.into());
        fields.insert("songCount".into(), song_count.into());
        fields.insert("duration".into(), (i64::from(song_count) * 210).into());
        fields.insert("comment".into(), "Generated by Octo from your library".into());
        fields.insert("created".into(), millis(&mix.period_start_utc).into());
        fields.insert("changed".into(), millis(&mix.period_start_utc).into());
        fields.insert("coverArt".into(), mix.id.clone().into());
        fields.insert("readonly".into(), true.into());
        fields.insert("validUntil".into(), millis(&mix.period_end_utc).into());
        fields
    }

    fn create_generated_playlist_response(
        &self,
        format: &str,
        mix: &GeneratedPlaylist,
        settings: &GeneratedPlaylistSettings,
        entries: &[Node],
    ) -> SubsonicReply {
        let fields = self.generated_playlist_fields(mix, settings);
        self.create_entries_playlist_response(format, fields, entries)
    }

    fn create_library_action_outcome_response(
        &self,
        song_id: &str,
        outcome: &LibraryActionOutcome,
        action: &str,
    ) -> SubsonicReply {
        self.create_library_action_response(
            song_id,
            &to_lower_invariant(outcome.state.name()),
            outcome.detail.as_deref(),
            action,
        )
    }

    fn create_upgrades_response(&self, jobs: &[(UpgradeJob, Option<f64>)]) -> SubsonicReply {
        self.create_json_response(json!({
            "status": "ok",
            "version": SUBSONIC_VERSION,
            "type": "octo",
            "openSubsonic": true,
            "upgrades": jobs.iter().map(|(job, progress)| json!({
                "id": job.navidrome_id,
                "title": job.title,
                "artist": job.artist,
                "album": job.album,
                "state": job.state,
                "detail": job.detail,
                "progress": progress,
                "updatedAt": round_trip(&job.updated_utc),
            })).collect::<Vec<_>>(),
        }))
    }
}

/// The default action of C#'s `CreateLibraryActionResponse(songId, outcome)`.
pub const DEFAULT_LIBRARY_ACTION: &str = REMOVE_ACTION;

/// One acquisition on the wire. The field names are a contract with the Octo app; a rename
/// here breaks its progress ring. Nulls are sent as null rather than left out.
pub fn acquisition_json(row: &AcquisitionSnapshot) -> Fields {
    let mut fields = Fields::new();
    fields.insert("id".into(), row.id.clone().into());
    fields.insert("artist".into(), json!(row.artist));
    fields.insert("title".into(), json!(row.title));
    fields.insert("album".into(), json!(row.album));
    fields.insert("state".into(), to_lower_invariant(row.state.name()).into());
    fields.insert("progress".into(), json!(row.progress));
    fields.insert("bytesDone".into(), json!(row.bytes_done));
    fields.insert("bytesTotal".into(), json!(row.bytes_total));
    fields.insert("source".into(), json!(row.source));
    fields.insert("startedAt".into(), utc(&row.started_at).into());
    fields.insert("updatedAt".into(), utc(&row.updated_at).into());
    fields.insert("error".into(), json!(row.error));
    fields.insert("libraryId".into(), json!(row.library_id));
    // Added for the app's words beside the ring. Older apps ignore them.
    fields.insert("ahead".into(), json!(row.ahead));
    fields.insert("note".into(), json!(row.note));
    fields
}

/// `yyyy-MM-dd'T'HH:mm:ss'Z'`.
fn utc(value: &DateTime<Utc>) -> String {
    value.format("%Y-%m-%dT%H:%M:%SZ").to_string()
}

/// `yyyy-MM-ddTHH:mm:ss.fffZ`.
fn millis(value: &DateTime<Utc>) -> String {
    value.format("%Y-%m-%dT%H:%M:%S%.3fZ").to_string()
}

/// `DateTime.ToString("O")` of a UTC time: seven fraction digits and `Z`.
fn round_trip(value: &DateTime<Utc>) -> String {
    format!(
        "{}.{:07}Z",
        value.format("%Y-%m-%dT%H:%M:%S"),
        value.timestamp_subsec_nanos() / 100
    )
}

#[cfg(test)]
mod tests {
    use chrono::TimeZone;
    use octo_subsonic::ReplyKind;

    use super::*;
    use crate::services::common::acquisition_tracker::AcquisitionState;
    use crate::services::library::LibraryActionState;

    fn builder() -> SubsonicResponseBuilder {
        new_subsonic_response_builder(
            Arc::new(ExternalIdRegistry::in_memory()),
            &SubsonicSettings::default(),
        )
    }

    #[test]
    fn the_registry_mints_the_ids_of_rows_without_one() {
        let registry = Arc::new(ExternalIdRegistry::in_memory());
        let builder = new_subsonic_response_builder(registry.clone(), &SubsonicSettings::default());
        let row = builder.convert_song_to_json(&octo_core::models::domain::Song {
            id: "s".into(),
            title: "Borealis".into(),
            artist: "Aurora Vale".into(),
            ..Default::default()
        });
        let album_id = row["albumId"].as_str().expect("album id");
        let routing = registry.lookup(album_id).expect("registered").snapshot();
        assert_eq!(routing.album.as_deref(), Some("Borealis"));
        assert_eq!(routing.artist.as_deref(), Some("Aurora Vale"));
        assert!(
            registry
                .lookup(row["artistId"].as_str().expect("artist id"))
                .is_some()
        );
    }

    #[test]
    fn acquisitions_write_every_field_with_nulls() {
        let at = Utc.with_ymd_and_hms(2026, 10, 4, 8, 7, 45).unwrap() + chrono::Duration::milliseconds(123);
        let row = AcquisitionSnapshot {
            id: "deezer:1".into(),
            artist: Some("A".into()),
            state: AcquisitionState::Downloading,
            progress: Some(0.25),
            bytes_done: Some(10),
            started_at: at,
            updated_at: at,
            ahead: Some(2),
            ..Default::default()
        };
        let reply = builder().create_acquisitions_response(&[row]);
        assert_eq!(reply.kind, ReplyKind::Json);
        assert_eq!(
            reply.text(),
            concat!(
                r#"{"subsonic-response":{"status":"ok","version":"1.16.1","type":"octo","acquisitions":{"acquisition":[{"#,
                r#""id":"deezer:1","artist":"A","title":null,"album":null,"state":"downloading","progress":0.25,"#,
                r#""bytesDone":10,"bytesTotal":null,"source":null,"startedAt":"2026-10-04T08:07:45Z","#,
                r#""updatedAt":"2026-10-04T08:07:45Z","error":null,"libraryId":null,"ahead":2,"note":null}]}}}"#
            )
        );
    }

    #[test]
    fn library_action_outcomes_and_upgrades_answer_in_json() {
        let outcome = LibraryActionOutcome::new(LibraryActionState::Rehearsed, Some("dry run".into()));
        assert_eq!(
            builder()
                .create_library_action_outcome_response("s1", &outcome, DEFAULT_LIBRARY_ACTION)
                .text(),
            r#"{"subsonic-response":{"status":"ok","version":"1.16.1","type":"octo","openSubsonic":true,"libraryAction":{"id":"s1","action":"remove","state":"rehearsed","detail":"dry run"}}}"#
        );
        let job = UpgradeJob {
            navidrome_id: "n1".into(),
            title: Some("T".into()),
            state: "working".into(),
            updated_utc: Utc.with_ymd_and_hms(2026, 10, 4, 8, 7, 45).unwrap()
                + chrono::Duration::nanoseconds(123_456_700),
            ..Default::default()
        };
        assert_eq!(
            builder().create_upgrades_response(&[(job, Some(0.5))]).text(),
            r#"{"subsonic-response":{"status":"ok","version":"1.16.1","type":"octo","openSubsonic":true,"upgrades":[{"id":"n1","title":"T","artist":null,"album":null,"state":"working","detail":null,"progress":0.5,"updatedAt":"2026-10-04T08:07:45.1234567Z"}]}}"#
        );
    }

    #[test]
    fn a_generated_mix_is_a_read_only_playlist_of_navidromes_songs() {
        let start = Utc.with_ymd_and_hms(2026, 10, 1, 0, 0, 0).unwrap();
        let mix = GeneratedPlaylist {
            id: "og1".into(),
            name: "Rock mix".into(),
            owner: "alice".into(),
            pool_size: 10,
            period_start_utc: start,
            period_end_utc: start + chrono::Duration::days(7),
            ..Default::default()
        };
        let settings = GeneratedPlaylistSettings::default();
        let fields = builder().generated_playlist_fields(&mix, &settings);
        let count = settings.effective_track_count().min(10);
        assert_eq!(fields["songCount"], count);
        assert_eq!(fields["duration"], i64::from(count) * 210);
        assert_eq!(fields["validUntil"], "2026-10-08T00:00:00.000Z");
        let entries = [Node::parse(r#"{"id":"n1","duration":200}"#).expect("JSON")];
        assert_eq!(
            builder()
                .create_generated_playlist_response("json", &mix, &settings, &entries)
                .text(),
            r#"{"subsonic-response":{"status":"ok","version":"1.16.1","playlist":{"id":"og1","name":"Rock mix","owner":"alice","public":false,"songCount":1,"duration":200,"comment":"Generated by Octo from your library","created":"2026-10-01T00:00:00.000Z","changed":"2026-10-01T00:00:00.000Z","coverArt":"og1","readonly":true,"validUntil":"2026-10-08T00:00:00.000Z","entry":[{"id":"n1","duration":200}]}}}"#
        );
    }
}
